### ISSUE TITLE
How to configure 

### ISSUE THREAD

**Issue by stecusin** [Chrischi-/tradegate-stock-info-for-scriptable#1]
Can you help to configure the script ?

I don’t understand how to edit the code to insert this:

Widget Parameter (ISIN;EK;smoothPath(0|1))

Thank you !!

**Comment by Chrischi-** [comment]
@stecusin 
you don't have to edit the code.

You enter the data (e.g.: `US6700024010;50.0;1`) into the widget Parameter of Scriptable.

ISIN = International Securities Identification Number
EK = purchase price
smoothPath: 0 = off; 1 = on

I hope this helps

**Comment by stecusin** [comment]
Thank you !
